apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  # 4 Реплики для пиковой нагрузки, 8 для сверхпиковой
  replicas: 4
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: loader
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        # Эта команда запускает 10 бесконечных циклов wget в фоне параллельно.
        # Это создает гораздо более интенсивную нагрузку, чем один цикл.
        args:
          - "for i in $(seq 1 10); do while true; do wget -q -O- http://webapp-service; done & done; wait"
        resources:
          limits:
            # Увеличиваем лимит для одной реплики, т.к. она теперь делает больше работы
            cpu: "500m"