# Имя нашего пайплайна
name: Build and Push Docker Image

# Триггер: запускать этот пайплайн при каждом push в ветку 'main'
on:
  push:
    branches: [ "main" ]

# Задачи, которые нужно выполнить
jobs:
  build-and-push:
    # Запускать на виртуальной машине с последней версией Ubuntu
    runs-on: ubuntu-latest
    
    # Шаги выполнения
    steps:
      # Шаг 1: Скачиваем код нашего репозитория на виртуальную машину
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Логинимся в Docker Hub
      # Он будет использовать секреты DOCKERHUB_USERNAME и DOCKERHUB_TOKEN, которые мы создали
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Шаг 3: Собираем и пушим Docker-образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Искать Dockerfile в корне репозитория
          push: true # Указываем, что образ нужно не только собрать, но и запушить
          # Присваиваем образу имя: логин/имя_репозитория:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mindbox-sre-project:latest